language: clojure
script:
  - lein check-deps
  - lein compile
  - lein lint
  - lein test
  - lein uberjar
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
notifications:
  email:
      - oubiwann@gmail.com
